// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: customer.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import GRPCShared

// MARK: - everything.customer.v1.CustomerService

/// Namespace containing generated types for the "everything.customer.v1.CustomerService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Everything_Customer_V1_CustomerService: Sendable {
    /// Service descriptor for the "everything.customer.v1.CustomerService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "everything.customer.v1.CustomerService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "HealthCheck" metadata.
        public enum HealthCheck: Sendable {
            /// Request type for "HealthCheck".
            public typealias Input = Everything_Customer_V1_HealthCheckRequest
            /// Response type for "HealthCheck".
            public typealias Output = Everything_Customer_V1_HealthCheckResponse
            /// Descriptor for "HealthCheck".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "everything.customer.v1.CustomerService"),
                method: "HealthCheck"
            )
        }
        /// Descriptors for all methods in the "everything.customer.v1.CustomerService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            HealthCheck.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "everything.customer.v1.CustomerService" service.
    public static let everything_customer_v1_CustomerService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "everything.customer.v1.CustomerService")
}

// MARK: everything.customer.v1.CustomerService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Everything_Customer_V1_CustomerService {
    /// Streaming variant of the service protocol for the "everything.customer.v1.CustomerService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Customer Service - Manages customer profiles, favorites, and loyalty
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "HealthCheck" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Health check endpoint
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Everything_Customer_V1_HealthCheckRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Everything_Customer_V1_HealthCheckResponse` messages.
        func healthCheck(
            request: GRPCCore.StreamingServerRequest<Everything_Customer_V1_HealthCheckRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Everything_Customer_V1_HealthCheckResponse>
    }

    /// Service protocol for the "everything.customer.v1.CustomerService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Customer Service - Manages customer profiles, favorites, and loyalty
    public protocol ServiceProtocol: Everything_Customer_V1_CustomerService.StreamingServiceProtocol {
        /// Handle the "HealthCheck" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Health check endpoint
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Everything_Customer_V1_HealthCheckRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Everything_Customer_V1_HealthCheckResponse` message.
        func healthCheck(
            request: GRPCCore.ServerRequest<Everything_Customer_V1_HealthCheckRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Everything_Customer_V1_HealthCheckResponse>
    }

    /// Simple service protocol for the "everything.customer.v1.CustomerService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Customer Service - Manages customer profiles, favorites, and loyalty
    public protocol SimpleServiceProtocol: Everything_Customer_V1_CustomerService.ServiceProtocol {
        /// Handle the "HealthCheck" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Health check endpoint
        ///
        /// - Parameters:
        ///   - request: A `Everything_Customer_V1_HealthCheckRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Everything_Customer_V1_HealthCheckResponse` to respond with.
        func healthCheck(
            request: Everything_Customer_V1_HealthCheckRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Everything_Customer_V1_HealthCheckResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Everything_Customer_V1_CustomerService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Everything_Customer_V1_CustomerService.Method.HealthCheck.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Everything_Customer_V1_HealthCheckRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Everything_Customer_V1_HealthCheckResponse>(),
            handler: { request, context in
                try await self.healthCheck(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Everything_Customer_V1_CustomerService.ServiceProtocol {
    public func healthCheck(
        request: GRPCCore.StreamingServerRequest<Everything_Customer_V1_HealthCheckRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Everything_Customer_V1_HealthCheckResponse> {
        let response = try await self.healthCheck(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Everything_Customer_V1_CustomerService.SimpleServiceProtocol {
    public func healthCheck(
        request: GRPCCore.ServerRequest<Everything_Customer_V1_HealthCheckRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Everything_Customer_V1_HealthCheckResponse> {
        return GRPCCore.ServerResponse<Everything_Customer_V1_HealthCheckResponse>(
            message: try await self.healthCheck(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}