package import GRPCClient

package typealias OrderServiceClient = Everything_Order_V1_OrderService.ClientProtocol
package typealias CustomerServiceClient = Everything_Customer_V1_CustomerService.ClientProtocol
