// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Health check endpoint
    ///
    /// - Remark: HTTP `GET /health`.
    /// - Remark: Generated from `#/paths//health/get(healthCheck)`.
    func healthCheck(_ input: Operations.healthCheck.Input) async throws -> Operations.healthCheck.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Health check endpoint
    ///
    /// - Remark: HTTP `GET /health`.
    /// - Remark: Generated from `#/paths//health/get(healthCheck)`.
    public func healthCheck(headers: Operations.healthCheck.Input.Headers = .init()) async throws -> Operations.healthCheck.Output {
        try await healthCheck(Operations.healthCheck.Input(headers: headers))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    /// Local development server
    public enum Server1 {
        /// Local development server
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://localhost:8080",
                variables: []
            )
        }
    }
    /// Local development server
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://localhost:8080",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/HealthResponse`.
        public struct HealthResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/HealthResponse/status`.
            @frozen public enum statusPayload: String, Codable, Hashable, Sendable, CaseIterable {
                case ok = "ok"
                case degraded = "degraded"
                case down = "down"
            }
            /// - Remark: Generated from `#/components/schemas/HealthResponse/status`.
            public var status: Components.Schemas.HealthResponse.statusPayload
            /// - Remark: Generated from `#/components/schemas/HealthResponse/timestamp`.
            public var timestamp: Foundation.Date?
            /// Creates a new `HealthResponse`.
            ///
            /// - Parameters:
            ///   - status:
            ///   - timestamp:
            public init(
                status: Components.Schemas.HealthResponse.statusPayload,
                timestamp: Foundation.Date? = nil
            ) {
                self.status = status
                self.timestamp = timestamp
            }
            public enum CodingKeys: String, CodingKey {
                case status
                case timestamp
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// Health check endpoint
    ///
    /// - Remark: HTTP `GET /health`.
    /// - Remark: Generated from `#/paths//health/get(healthCheck)`.
    public enum healthCheck {
        public static let id: Swift.String = "healthCheck"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/health/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.healthCheck.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.healthCheck.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.healthCheck.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.healthCheck.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/health/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/health/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.HealthResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HealthResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.healthCheck.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.healthCheck.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Service is healthy
            ///
            /// - Remark: Generated from `#/paths//health/get(healthCheck)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.healthCheck.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.healthCheck.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
